### ISSUE TITLE
[Discussion] "Missing Quest Tracker" / Info on the new quest tracker in `0.7.7`

### ISSUE THREAD

**Issue by RavenknightDM** [typhonjs-fvtt/typhonjs-quest-log#132]
Hiya, thanks for the mod.
I've just updated to 0.7.7 and everything is looking good except that the floating Quest Tracker is gone, both for me and my players. Is there a way to re-activate it that I've missed? I believe that it used to appear automatically.

**Comment by typhonrt** [comment]
Hi @RavenknightDM. Indeed it no longer automatically appears and has been redesigned significantly. There are two ways to open the quest tracker. The first is the icon under opening the quest log when "journal notes" is selected in the menu bar. The second is a macro from the new macro compendiums. Please see these two pictures below on how to open the new quest tracker. Also please check out the release video which describes a lot of things in detail:
- [New Quest Tracker](https://www.youtube.com/watch?v=lfSYJXVQAcE&t=281s)
- [Quest Tracker enable / disable macro](https://www.youtube.com/watch?v=lfSYJXVQAcE&t=806s)

Picts:
![fql-quest-tracker-icon](https://user-images.githubusercontent.com/311473/132955102-d1c576e9-61b8-40f2-84d8-d33497095750.png)

![fql-enable-quest-tracker](https://user-images.githubusercontent.com/311473/132955108-ea2caab7-57b7-4f86-89ae-0ecac2e6a224.png)

Please keep this issue open so that hopefully others see this information. This is the second time this issue has been brought up, but is worth keeping up as a "discussion" issue so others don't file it again. 

I do hope you enjoy the new quest tracker as it really provides some great user experience aspects. Do check out the video too about the new primary quest feature with the quest tracker.

**Comment by RavenknightDM** [comment]
Ah, missed that. :D Thank you so very much for the clarification. ( And the mod! )

**Comment by typhonrt** [comment]
I'm just going to close this discussion for now. Happy questing!
