### ISSUE TITLE
Region/City box information/sort option

### ISSUE THREAD

**Issue by MarceloCortezz** [typhonjs-fvtt/typhonjs-quest-log#21]
Hi Forien,

I was thinking here and I don't know if this was suggested before but having a Region/City/Locale text box where you get the quest (besides the NPC) where you can type the city, for instance, this quest will be available. And a sort type feature that shows you (or filter) quests available in that region/city.

**Comment by Shuggaloaf** [comment]
I'd like to 2nd this as I think it would be _extremely_ useful! Giving the players an option to sort/filter by location (or just a "catch-all" field) would be great!

@MarceloCortezz I have a work-around for you for now. It doesn't give you any filtering, but you can at least easily see locations.
I have a lot of quests that are of various "suggested" party levels. Rather than spoon feed my players a few quests at a time I have made all available. My players are new, and are used to video game RPGs, so I'm kind of doing a Witcher 3 style of approaching quests - lots of side/smaller quests of varying level. 
They can accept quests of any level, but I show the suggested level in the title. I have the level as the first part of the quest title, so it sorts by that. You could do the same but instead of level, make it the location. (I have my location at the end of the quest title, so they can see both, but for them the level is more important). Since that probably sounded confusing as hell, here's a couple pics:
<img src="https://user-images.githubusercontent.com/79543184/122835317-1f8ebf00-d2be-11eb-84d4-90a403c0710a.png" alt="pic" width="20%"/>
_Some lower level side quests_

You can also use special characters to force specific sorting. These are some "Alchemist Guild" quests I setup - basically monster part harvesting that players can do as a small add-on to existing quests. Since pretty much most monsters they are likely to run into need to be available, I wanted a way to put them all at the end of the quest log so they wouldn't get mixed in with regular quests and clutter up everything. Adding the special character "omega" puts these quests at the end of the list (fittingly) 
<img src="https://user-images.githubusercontent.com/79543184/122835453-5a90f280-d2be-11eb-98de-fa485942a6e7.png" alt="pic" width="20%"/>
_Available list of monsters for harvesting. Various "monster parts" are listed inside each quest with a gold value_

**Comment by Shuggaloaf** [comment]
I'd like to 2nd this as I think it would be _extremely_ useful! Giving the players an option to sort/filter by location (or just a "catch-all" field) would be great!

&nbsp;
&nbsp;
**For @MarceloCortezz (and anyone else interested)** 
<hr/>

I have a **_kinda/sorta work-around_** for you for now. It doesn't give you any filtering, but you can at least easily see locations.
(This is long - sorry!) I have a lot of quests that are of various "suggested" party levels. Rather than spoon feed my players a few quests at a time I have made all available. My players are new, and are used to video game RPGs, so I'm kind of doing a Witcher 3 style of approaching quests - lots of side/smaller quests of varying level. 
They can accept quests of any level, but I show the suggested level in the title. I have the level as the first part of the quest title, so it sorts by that. You could do the same but instead of level, make it the location. (I have my location at the end of the quest title, so they can see both, but for them the level is more important). Since that probably sounded confusing as hell, here's a couple pics:
<img src="https://user-images.githubusercontent.com/79543184/122835317-1f8ebf00-d2be-11eb-84d4-90a403c0710a.png" alt="pic" width="25%"/>
_Some lower level side quests_

You can also use special characters to force specific sorting. These are some "Alchemist Guild" quests I setup - basically monster part harvesting that players can do as a small add-on to existing quests. Since pretty much most monsters they are likely to run into need to be available, I wanted a way to put them all at the end of the quest log so they wouldn't get mixed in with regular quests and clutter up everything. Adding the special character "omega" puts these quests at the end of the list (fittingly) 
<img src="https://user-images.githubusercontent.com/79543184/122836984-4f8b9180-d2c1-11eb-8de3-ab3620c45318.png" alt="pic" width="15%"/>
_Available list of monsters for harvesting. Various "monster parts" are listed inside each quest with a gold value_

**Comment by MarceloCortezz** [comment]
Hmmm, that's great workaround. Thank you!

**Comment by Shuggaloaf** [comment]
> Hmmm, that's great workaround. Thank you!

Well I wouldn't say great, but it's something. Haha But I appreciate you saying so. :-)

**Comment by typhonrt** [comment]
Hi folks.. I'm just streamlining the issues. While this issue is being closed Issue #103 tracks the enhancement mentioned here.
